import React, { useEffect, useMemo, useState } from 'react'
import ReactDOM from 'react-dom/client'
import { BrowserRouter, Link, NavLink, Route, Routes, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { editions, categories, adminRows } from './data'
import './styles.css'

const Brand = ({ compact=false }) => <Link to="/" className={`brand ${compact ? 'brand--compact' : ''}`}><span className="brand-mark">UNIEURO</span><span className="brand-rule"/><span className="brand-sub">REVISTA CIENTÍFICA<br/>DE PSICOLOGIA</span></Link>
const Icon = ({children}) => <span className="icon" aria-hidden="true">{children}</span>

function Header(){
  const nav = useNavigate(); const [q,setQ]=useState('')
  function submit(e){e.preventDefault(); if(q.trim()) nav(`/buscar?q=${encodeURIComponent(q.trim())}`)}
  return <header className="site-header"><div className="container header-inner"><Brand/><nav className="main-nav"><NavLink to="/">Início</NavLink><NavLink to="/edicoes">Edições</NavLink><NavLink to="/temas">Temas</NavLink><NavLink to="/acervo">Acervo</NavLink></nav><form className="top-search" onSubmit={submit}><Icon>⌕</Icon><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar na revista..." aria-label="Buscar"/></form></div></header>
}

function Footer(){ return <footer className="site-footer"><div className="container footer-grid"><div><Brand compact/></div><nav><Link to="/sobre">Sobre a Revista</Link><a href="#">Normas para Autores</a><a href="#">Política Editorial</a><a href="#">Contato</a></nav><strong>Ciência. Pessoas. Possibilidades.</strong></div></footer> }
function PublicLayout({children}){ return <><Header/>{children}<Footer/></> }
function SectionTitle({title,sub,action}){return <div className="section-heading"><div><h2>{title}</h2>{sub&&<span>{sub}</span>}</div>{action}</div>}
function Cover({edition,className=''}){return <img className={`cover ${className}`} src={edition.cover} alt={`Capa: ${edition.title}`}/>} 

function Home(){const featured=editions[0]; return <PublicLayout><main>
  <section className="hero"><div className="container hero-grid"><Cover edition={featured} className="hero-cover"/><div className="hero-copy"><div className="eyebrow">EDIÇÃO EM DESTAQUE</div><h1>Revista Científica de Psicologia</h1><p className="meta-lg">{featured.issue} <b>•</b> {featured.month} de {featured.year}</p><h3>{featured.title}</h3><p>{featured.subtitle}</p><p className="subtle">{featured.pages} páginas <span>│</span> ISSN 2675-0000</p><div className="actions"><Link className="btn btn-primary" to={`/ler/${featured.slug}`}>▣ &nbsp; Ler edição</Link><a className="btn btn-outline" href="#" onClick={e=>e.preventDefault()}>⇩ &nbsp; Baixar PDF</a></div></div><aside className="hero-note"><span className="red-rule"/><h2>Conhecimento<br/>para uma sociedade<br/>mais humana.</h2><p>A revista publica pesquisas, reflexões e práticas que contribuem para o desenvolvimento humano e uma sociedade mais justa.</p></aside></div></section>
  <section className="container section"><SectionTitle title="Edições recentes" action={<Link className="text-link" to="/edicoes">Ver todas as edições →</Link>}/><div className="recent-grid">{editions.slice(1,5).map(e=><article className="recent-card" key={e.id}><Cover edition={e}/><div><div className="issue">{e.issue}</div><div className="date">{e.month} de {e.year}</div><h3>{e.title}</h3><div className="subtle">{e.pages} páginas</div><Link className="text-link" to={`/edicoes/${e.slug}`}>Ver edição →</Link></div></article>)}</div></section>
  <section className="container section compact-section"><SectionTitle title="Explore por tema"/><div className="topic-grid">{categories.slice(0,5).map(c=><Link className="topic-card" key={c.slug} to={`/temas/${c.slug}`}><Icon>{c.icon}</Icon><span>{c.name}</span><b>→</b></Link>)}</div></section>
  <section className="container archive-strip"><h2>Acervo</h2>{[2026,2025,2024,2023,2022,2021,2020,2019,2018,2017].map((y,i)=><Link key={y} className={i===0?'active-year':''} to={`/acervo?ano=${y}`}>{i===0?'Todos':y}</Link>)}<Link className="archive-all" to="/acervo">Ver acervo completo →</Link></section>
</main></PublicLayout>}

function Editions(){const [year,setYear]=useState('Todos'); const years=[...new Set(editions.map(e=>e.year))]; const list=year==='Todos'?editions:editions.filter(e=>e.year===+year); return <PublicLayout><main className="container page"><div className="page-heading"><div><div className="eyebrow">PUBLICAÇÕES</div><h1>Edições</h1><p>Explore todas as edições da Revista Científica de Psicologia.</p></div><select value={year} onChange={e=>setYear(e.target.value)}><option>Todos</option>{years.map(y=><option key={y}>{y}</option>)}</select></div><div className="cover-grid">{list.map(e=><Link to={`/edicoes/${e.slug}`} className="edition-card" key={e.id}><Cover edition={e}/><div className="issue">{e.issue}</div><div className="date">{e.month} de {e.year}</div><h3>{e.title}</h3></Link>)}</div></main></PublicLayout>}

function EditionDetail(){const {slug}=useParams(); const e=editions.find(x=>x.slug===slug)||editions[0]; const [rating,setRating]=useState(0); return <PublicLayout><main className="container page"><Link className="back" to="/edicoes">← Todas as edições</Link><div className="detail-grid"><Cover edition={e} className="detail-cover"/><div className="detail-copy"><div className="eyebrow">{e.issue} · {e.month.toUpperCase()} {e.year}</div><h1>{e.title}</h1><p className="lead">{e.subtitle}</p><div className="chip-row">{e.categories.map(c=><span className="chip" key={c}>{c}</span>)}</div><dl className="details"><div><dt>Páginas</dt><dd>{e.pages}</dd></div><div><dt>Avaliação</dt><dd>★ {e.rating} ({e.ratings})</dd></div><div><dt>Formato</dt><dd>PDF</dd></div></dl><div className="actions"><Link className="btn btn-primary" to={`/ler/${e.slug}`}>▣ &nbsp; Ler revista</Link><button className="btn btn-outline">⇩ &nbsp; Baixar PDF</button></div></div></div><div className="content-cols"><article><h2>Sobre esta edição</h2><p>{e.subtitle} Esta edição reúne pesquisas, ensaios e reflexões produzidos no contexto acadêmico do curso de Psicologia.</p><h2>Informações da publicação</h2><p>Centro Universitário UNIEURO · Curso de Psicologia · Revista científica digital.</p></article><aside className="rating-box"><h3>Avalie esta edição</h3><p>Como foi sua experiência de leitura?</p><div className="stars">{[1,2,3,4,5].map(n=><button key={n} onClick={()=>setRating(n)} className={n<=rating?'on':''}>★</button>)}</div>{rating>0&&<small>Avaliação registrada: {rating}/5</small>}</aside></div></main></PublicLayout>}

function Reader(){const {slug}=useParams(); const e=editions.find(x=>x.slug===slug)||editions[0]; const [page,setPage]=useState(1); const [zoom,setZoom]=useState(100); const total=e.pages; const prev=()=>setPage(p=>Math.max(1,p-2)); const next=()=>setPage(p=>Math.min(total,p+2)); useEffect(()=>{const f=(ev)=>{if(ev.key==='ArrowRight')next(); if(ev.key==='ArrowLeft')prev()}; addEventListener('keydown',f); return ()=>removeEventListener('keydown',f)},[]); return <div className="reader-shell"><header className="reader-top"><Link to={`/edicoes/${e.slug}`}>← Voltar</Link><div><strong>{e.title}</strong><span>{e.issue}</span></div><div><button title="Download">⇩</button><button title="Mais">•••</button></div></header><div className="reader-body"><button className="page-arrow left" onClick={prev}>‹</button><div className="spread" style={{transform:`scale(${zoom/100})`}}><ReaderPage n={page} title={e.title}/>{page<total&&<ReaderPage n={page+1} title={e.title}/>}</div><button className="page-arrow right" onClick={next}>›</button></div><footer className="reader-controls"><button onClick={prev}>‹</button><span>{page}–{Math.min(page+1,total)} / {total}</span><span className="control-spacer"/><button onClick={()=>setZoom(z=>Math.max(60,z-10))}>−</button><span>{zoom}%</span><button onClick={()=>setZoom(z=>Math.min(160,z+10))}>+</button><button onClick={next}>›</button></footer></div>}
function ReaderPage({n,title}){return <div className="paper"><div className="paper-kicker">REVISTA CIENTÍFICA DE PSICOLOGIA · UNIEURO</div><h2>{n===1?title:`Capítulo ${Math.ceil(n/8)}`}</h2>{n===1?<><div className="paper-art"><span/><span/><span/></div><p className="paper-lead">Pesquisa, reflexão e prática em Psicologia.</p></>:<><p>Este espaço representa uma página do PDF carregada pelo leitor. No produto final, cada página será renderizada sob demanda para manter bom desempenho mesmo em revistas extensas.</p><p>A interface mantém foco no conteúdo, com navegação discreta, zoom e leitura em página dupla no desktop.</p><div className="paper-block"/><p>O carregamento progressivo evita renderizar centenas de páginas de uma só vez.</p></>}<small>{n}</small></div>}

function SearchPage(){const [params]=useSearchParams(); const initial=params.get('q')||''; const [q,setQ]=useState(initial); const results=useMemo(()=>{const s=q.toLowerCase(); return !s?editions:editions.filter(e=>`${e.title} ${e.subtitle} ${e.categories.join(' ')}`.toLowerCase().includes(s))},[q]); return <PublicLayout><main className="container page"><div className="eyebrow">BUSCA</div><h1>Buscar publicações</h1><div className="search-large"><Icon>⌕</Icon><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Ex.: ansiedade, escola, desenvolvimento..."/></div><p className="subtle">{results.length} resultado(s){q&&<> para “{q}”</>}</p><div className="search-results">{results.map(e=><Link key={e.id} to={`/edicoes/${e.slug}`} className="search-result"><Cover edition={e}/><div><div className="eyebrow">{e.issue} · {e.year}</div><h2>{e.title}</h2><p>{e.subtitle}</p><div className="chip-row">{e.categories.map(c=><span className="chip" key={c}>{c}</span>)}</div></div></Link>)}{!results.length&&<div className="empty"><h2>Nenhuma publicação encontrada</h2><p>Tente um termo mais amplo.</p></div>}</div></main></PublicLayout>}

function Topics(){return <PublicLayout><main className="container page"><div className="eyebrow">NAVEGAÇÃO</div><h1>Temas</h1><p className="lead narrow">Explore o acervo pelas principais áreas da Psicologia.</p><div className="topic-list">{categories.map(c=><Link key={c.slug} to={`/temas/${c.slug}`}><span className="topic-big-icon">{c.icon}</span><div><h2>{c.name}</h2><p>{c.count} publicações</p></div><b>→</b></Link>)}</div></main></PublicLayout>}
function TopicDetail(){const {slug}=useParams(); const c=categories.find(x=>x.slug===slug)||categories[0]; const list=editions.filter(e=>e.categories.includes(c.name)); return <PublicLayout><main className="container page"><Link className="back" to="/temas">← Todos os temas</Link><div className="eyebrow">TEMA</div><h1>{c.name}</h1><p>{c.count} publicações no acervo.</p><div className="cover-grid">{(list.length?list:editions.slice(0,3)).map(e=><Link to={`/edicoes/${e.slug}`} className="edition-card" key={e.id}><Cover edition={e}/><div className="issue">{e.issue}</div><div className="date">{e.month} de {e.year}</div><h3>{e.title}</h3></Link>)}</div></main></PublicLayout>}

function Archive(){const [params,setParams]=useSearchParams(); const years=[...new Set(editions.map(e=>e.year))]; const y=+(params.get('ano')||years[0]); return <PublicLayout><main className="container page"><div className="eyebrow">HISTÓRICO</div><h1>Acervo</h1><p>As publicações permanecem disponíveis por ano, formando o histórico permanente da revista.</p><div className="year-tabs">{years.map(year=><button className={year===y?'active':''} onClick={()=>setParams({ano:year})} key={year}>{year}</button>)}</div><div className="archive-list">{editions.filter(e=>e.year===y).map(e=><Link key={e.id} to={`/edicoes/${e.slug}`}><div className="archive-month">{e.month.slice(0,3).toUpperCase()}</div><Cover edition={e}/><div><div className="issue">{e.issue}</div><h2>{e.title}</h2><p>{e.pages} páginas · {e.categories.join(' · ')}</p></div><b>→</b></Link>)}</div></main></PublicLayout>}

function About(){return <PublicLayout><main className="container page prose-page"><div className="eyebrow">INSTITUCIONAL</div><h1>Sobre a revista</h1><p className="lead">A Revista Científica de Psicologia do UNIEURO é um acervo digital voltado à divulgação de pesquisas e produções acadêmicas da área.</p><h2>Propósito</h2><p>Facilitar o acesso público às revistas produzidas pelos estudantes, mantendo as publicações organizadas, pesquisáveis e disponíveis para leitura e download.</p><h2>Curso de Psicologia</h2><p>Centro Universitário UNIEURO · Brasília, Distrito Federal.</p><h2>Modelo editorial</h2><p>As revistas são produzidas externamente e publicadas na plataforma após revisão administrativa. O sistema não edita o conteúdo do PDF.</p></main></PublicLayout>}

function AdminLogin(){const nav=useNavigate(); return <div className="login-page"><div className="login-card"><Brand/><div className="eyebrow">ÁREA RESTRITA</div><h1>Acesso administrativo</h1><p>Entre para gerenciar as publicações da revista.</p><label>E-mail<input defaultValue="fabricio@unieuro.edu.br"/></label><label>Senha<input type="password" defaultValue="12345678"/></label><button className="btn btn-primary full" onClick={()=>nav('/admin/dashboard')}>Entrar</button><Link to="/">← Voltar para a revista</Link></div></div>}

function AdminLayout({children,title,action}){return <div className="admin-shell"><aside className="admin-side"><Brand compact/><nav><NavLink to="/admin/dashboard">Dashboard</NavLink><NavLink to="/admin/publicacoes">Publicações</NavLink><NavLink to="/admin/publicacoes/nova">Nova publicação</NavLink><NavLink to="/admin/categorias">Categorias</NavLink><NavLink to="/admin/avaliacoes">Avaliações</NavLink><NavLink to="/admin/usuarios">Usuários</NavLink><NavLink to="/admin/configuracoes">Configurações</NavLink></nav><Link className="admin-exit" to="/">← Ver revista</Link></aside><div className="admin-main"><header className="admin-top"><div><span>Revista Científica de Psicologia</span><h1>{title}</h1></div><div className="admin-user">Professor Fabrício ▾</div></header>{action&&<div className="admin-action">{action}</div>}<div className="admin-content">{children}</div></div></div>}
function Dashboard(){return <AdminLayout title="Dashboard"><div className="stats"><Stat n="6" label="Publicadas"/><Stat n="1" label="Rascunho"/><Stat n="0" label="Arquivadas"/><Stat n="4,6" label="Avaliação média"/></div><Panel title="Últimas publicações"><AdminTable rows={adminRows.slice(0,5)}/></Panel></AdminLayout>}
function Stat({n,label}){return <div className="stat"><strong>{n}</strong><span>{label}</span></div>}
function Panel({title,children}){return <section className="panel"><div className="panel-title"><h2>{title}</h2></div>{children}</section>}
function AdminTable({rows=adminRows}){return <div className="table-wrap"><table><thead><tr><th>Publicação</th><th>Edição</th><th>Categoria</th><th>Status</th><th></th></tr></thead><tbody>{rows.map(e=><tr key={e.id}><td><div className="table-publication"><Cover edition={e}/><span>{e.title}</span></div></td><td>{e.issue}<small>{e.month} {e.year}</small></td><td>{e.categories?.[0]}</td><td><span className={`status ${e.status==='Publicada'?'published':'draft'}`}>{e.status}</span></td><td><Link to={`/admin/publicacoes/${e.id}`}>Editar →</Link></td></tr>)}</tbody></table></div>}
function AdminPublications(){const [q,setQ]=useState(''); const rows=adminRows.filter(r=>r.title.toLowerCase().includes(q.toLowerCase())); return <AdminLayout title="Publicações" action={<Link className="btn btn-primary" to="/admin/publicacoes/nova">+ Nova publicação</Link>}><div className="toolbar"><input placeholder="Buscar publicação" value={q} onChange={e=>setQ(e.target.value)}/><select><option>Todos os status</option><option>Publicada</option><option>Rascunho</option></select></div><Panel title={`${rows.length} publicações`}><AdminTable rows={rows}/></Panel></AdminLayout>}

function PublicationWizard(){const [step,setStep]=useState(1); const [file,setFile]=useState(null); const [form,setForm]=useState({title:'',issue:'',date:'',description:'',category:'Saúde Mental'}); return <AdminLayout title="Nova publicação"><div className="wizard"><div className="stepper">{['Arquivo','Informações','Capa','Revisão'].map((s,i)=><div className={step>=i+1?'active':''} key={s}><b>{i+1}</b><span>{s}</span></div>)}</div>{step===1&&<div className="wizard-card"><h2>Enviar revista</h2><p>Selecione o PDF final. Revistas longas são aceitas; o frontend não impõe limite de 50–100 páginas.</p><label className="upload-box"><input type="file" accept="application/pdf" onChange={e=>setFile(e.target.files[0])}/><strong>{file?file.name:'Arraste o PDF aqui ou clique para selecionar'}</strong><span>PDF · processamento progressivo</span></label></div>}{step===2&&<div className="wizard-card form-grid"><h2>Informações da publicação</h2><label>Título<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><div className="two"><label>Número da edição<input value={form.issue} onChange={e=>setForm({...form,issue:e.target.value})}/></label><label>Data<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label></div><label>Descrição<textarea rows="5" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Categoria<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{categories.map(c=><option key={c.slug}>{c.name}</option>)}</select></label></div>}{step===3&&<div className="wizard-card"><h2>Capa</h2><p>Por padrão, a primeira página do PDF será usada como capa.</p><div className="cover-choice"><Cover edition={editions[0]}/><div><button className="btn btn-outline">Usar primeira página</button><button className="text-button">Enviar outra imagem</button></div></div></div>}{step===4&&<div className="wizard-card"><h2>Revisar publicação</h2><div className="review"><Cover edition={editions[0]}/><dl><div><dt>Título</dt><dd>{form.title||'Nova publicação'}</dd></div><div><dt>Edição</dt><dd>{form.issue||'—'}</dd></div><div><dt>Categoria</dt><dd>{form.category}</dd></div><div><dt>Arquivo</dt><dd>{file?.name||'revista.pdf'}</dd></div></dl></div></div>}<div className="wizard-actions"><button className="btn btn-outline" disabled={step===1} onClick={()=>setStep(s=>Math.max(1,s-1))}>Voltar</button>{step<4?<button className="btn btn-primary" onClick={()=>setStep(s=>s+1)}>Continuar</button>:<><button className="btn btn-outline">Salvar rascunho</button><button className="btn btn-primary">Publicar</button></>}</div></div></AdminLayout>}

function EditPublication(){const {id}=useParams(); const e=adminRows.find(x=>x.id===+id)||adminRows[0]; return <AdminLayout title="Editar publicação" action={<Link className="btn btn-outline" to={`/edicoes/${e.slug}`}>Visualizar</Link>}><div className="edit-layout"><div className="panel form-grid"><label>Título<input defaultValue={e.title}/></label><div className="two"><label>Edição<input defaultValue={e.issue}/></label><label>Status<select defaultValue={e.status}><option>Publicada</option><option>Rascunho</option><option>Arquivada</option></select></label></div><label>Descrição<textarea rows="5" defaultValue={e.subtitle}/></label><label>Categoria<select defaultValue={e.categories[0]}>{categories.map(c=><option key={c.slug}>{c.name}</option>)}</select></label><div className="actions"><button className="btn btn-primary">Salvar alterações</button><button className="btn btn-danger">Arquivar</button></div></div><aside className="panel publication-preview"><Cover edition={e}/><p><strong>{e.pages}</strong> páginas</p><p>PDF processado</p></aside></div></AdminLayout>}

function AdminCategories(){return <AdminLayout title="Categorias" action={<button className="btn btn-primary">+ Categoria</button>}><Panel title="Categorias da revista"><div className="simple-list">{categories.map(c=><div key={c.slug}><div><strong>{c.name}</strong><span>{c.count} revistas</span></div><button>Editar</button></div>)}</div></Panel></AdminLayout>}
function AdminRatings(){return <AdminLayout title="Avaliações"><div className="stats"><Stat n="4,6" label="Média geral"/><Stat n="204" label="Avaliações"/></div><Panel title="Por edição"><div className="simple-list">{editions.map(e=><div key={e.id}><div><strong>{e.title}</strong><span>{e.issue}</span></div><b>★ {e.rating} <small>{e.ratings} avaliações</small></b></div>)}</div></Panel></AdminLayout>}
function AdminUsers(){const users=[['Professor Fabrício','Administrador','Ativo'],['Maria Silva','Editor/Publicador','Ativo'],['João Costa','Colaborador','Ativo']]; return <AdminLayout title="Usuários" action={<button className="btn btn-primary">+ Usuário</button>}><Panel title="Acesso ao sistema"><div className="simple-list">{users.map(u=><div key={u[0]}><div><strong>{u[0]}</strong><span>{u[1]}</span></div><span className="status published">{u[2]}</span><button>Gerenciar</button></div>)}</div></Panel><div className="permission-note"><strong>Papéis</strong><p>Administrador: acesso total. Editor/Publicador: cria, edita e publica. Colaborador: cria e edita rascunhos.</p></div></AdminLayout>}
function AdminSettings(){return <AdminLayout title="Configurações"><div className="settings-grid"><Panel title="Revista"><div className="form-grid"><label>Nome<input defaultValue="Revista Científica de Psicologia"/></label><label>Descrição<textarea rows="4" defaultValue="Pesquisa, reflexão e prática em Psicologia."/></label><button className="btn btn-primary">Salvar</button></div></Panel><Panel title="Publicação"><Toggle label="Avaliações"/><Toggle label="Downloads"/><Toggle label="Exibir ISSN"/></Panel><Panel title="Institucional"><div className="form-grid"><label>Instituição<input defaultValue="Centro Universitário UNIEURO"/></label><label>Curso<input defaultValue="Psicologia"/></label><label>Contato<input defaultValue="psicologia@unieuro.edu.br"/></label></div></Panel></div></AdminLayout>}
function Toggle({label}){const [on,setOn]=useState(true); return <button className="toggle-row" onClick={()=>setOn(!on)}><span>{label}</span><i className={on?'on':''}><b/></i></button>}

function NotFound(){return <PublicLayout><main className="container page empty"><h1>Página não encontrada</h1><Link className="btn btn-primary" to="/">Voltar ao início</Link></main></PublicLayout>}

function App(){return <Routes><Route path="/" element={<Home/>}/><Route path="/edicoes" element={<Editions/>}/><Route path="/edicoes/:slug" element={<EditionDetail/>}/><Route path="/ler/:slug" element={<Reader/>}/><Route path="/buscar" element={<SearchPage/>}/><Route path="/temas" element={<Topics/>}/><Route path="/temas/:slug" element={<TopicDetail/>}/><Route path="/acervo" element={<Archive/>}/><Route path="/sobre" element={<About/>}/><Route path="/admin/login" element={<AdminLogin/>}/><Route path="/admin/dashboard" element={<Dashboard/>}/><Route path="/admin/publicacoes" element={<AdminPublications/>}/><Route path="/admin/publicacoes/nova" element={<PublicationWizard/>}/><Route path="/admin/publicacoes/:id" element={<EditPublication/>}/><Route path="/admin/categorias" element={<AdminCategories/>}/><Route path="/admin/avaliacoes" element={<AdminRatings/>}/><Route path="/admin/usuarios" element={<AdminUsers/>}/><Route path="/admin/configuracoes" element={<AdminSettings/>}/><Route path="*" element={<NotFound/>}/></Routes>}

ReactDOM.createRoot(document.getElementById('root')).render(<React.StrictMode><BrowserRouter><App/></BrowserRouter></React.StrictMode>)
